
ms: 0.05 | Mt: 1 | dcm: 14.00 | layer: 2 | Epoch: 0/100
Traceback (most recent call last):
  File "main.py", line 215, in <module>
    accu_s = test(source_dataset_name)
  File "/home/huseyin/fungtion/dannpy_yeniden/DANN_py3/test.py", line 86, in test
    class_output, _ = my_net(input_data=t_img, alpha=alpha)
  File "/home/huseyin/anaconda3/envs/dannpy5/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/huseyin/fungtion/dannpy_yeniden/DANN_py3/model.py", line 53, in forward
    feature = self.feature(input_data)
  File "/home/huseyin/anaconda3/envs/dannpy5/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/huseyin/anaconda3/envs/dannpy5/lib/python3.8/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/home/huseyin/anaconda3/envs/dannpy5/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/huseyin/anaconda3/envs/dannpy5/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 419, in forward
    return self._conv_forward(input, self.weight)
  File "/home/huseyin/anaconda3/envs/dannpy5/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 415, in _conv_forward
    return F.conv2d(input, weight, self.bias, self.stride,
RuntimeError: CUDA out of memory. Tried to allocate 252.00 MiB (GPU 0; 1.95 GiB total capacity; 748.53 MiB already allocated; 180.81 MiB free; 1.29 GiB reserved in total by PyTorch)