Ms: 40 | Mt: 40 | dcm: 0.02 | layer: 3 | Epoch: 0/300
Accuracy of the mnist dataset: 0.071900
Accuracy of the mnist_m dataset: 0.086990
Ms: 40 | Mt: 40 | dcm: 0.02 | layer: 3 | Epoch: 1/300
Accuracy of the mnist dataset: 0.086400
Accuracy of the mnist_m dataset: 0.089879
Ms: 40 | Mt: 40 | dcm: 0.02 | layer: 3 | Epoch: 2/300
Accuracy of the mnist dataset: 0.097800
Accuracy of the mnist_m dataset: 0.090212
Ms: 40 | Mt: 40 | dcm: 0.02 | layer: 3 | Epoch: 3/300
Accuracy of the mnist dataset: 0.119200
Accuracy of the mnist_m dataset: 0.091656
Ms: 40 | Mt: 40 | dcm: 0.02 | layer: 3 | Epoch: 4/300
Accuracy of the mnist dataset: 0.094200
Accuracy of the mnist_m dataset: 0.089657
Ms: 40 | Mt: 40 | dcm: 0.02 | layer: 3 | Epoch: 5/300
Accuracy of the mnist dataset: 0.080700
Accuracy of the mnist_m dataset: 0.089768
Ms: 40 | Mt: 40 | dcm: 0.02 | layer: 3 | Epoch: 6/300
Accuracy of the mnist dataset: 0.081400
Accuracy of the mnist_m dataset: 0.089546
Ms: 40 | Mt: 40 | dcm: 0.02 | layer: 3 | Epoch: 7/300
Accuracy of the mnist dataset: 0.088900
Accuracy of the mnist_m dataset: 0.089435
Ms: 40 | Mt: 40 | dcm: 0.02 | layer: 3 | Epoch: 8/300
Accuracy of the mnist dataset: 0.085300
Accuracy of the mnist_m dataset: 0.092434
Ms: 40 | Mt: 40 | dcm: 0.02 | layer: 3 | Epoch: 9/300
Accuracy of the mnist dataset: 0.090900
Accuracy of the mnist_m dataset: 0.089546
Ms: 40 | Mt: 40 | dcm: 0.02 | layer: 3 | Epoch: 10/300
Accuracy of the mnist dataset: 0.089000
Accuracy of the mnist_m dataset: 0.090657
Ms: 40 | Mt: 40 | dcm: 0.02 | layer: 3 | Epoch: 11/300
Accuracy of the mnist dataset: 0.089900
Accuracy of the mnist_m dataset: 0.089768
Ms: 40 | Mt: 40 | dcm: 0.02 | layer: 3 | Epoch: 12/300
Accuracy of the mnist dataset: 0.089000
Accuracy of the mnist_m dataset: 0.089657
Ms: 40 | Mt: 40 | dcm: 0.02 | layer: 3 | Epoch: 13/300
Accuracy of the mnist dataset: 0.089800
Accuracy of the mnist_m dataset: 0.089657
Ms: 40 | Mt: 40 | dcm: 0.02 | layer: 3 | Epoch: 14/300
Accuracy of the mnist dataset: 0.097900
Accuracy of the mnist_m dataset: 0.089657
Ms: 40 | Mt: 40 | dcm: 0.02 | layer: 3 | Epoch: 15/300
Accuracy of the mnist dataset: 0.089300
Accuracy of the mnist_m dataset: 0.089657
Ms: 40 | Mt: 40 | dcm: 0.02 | layer: 3 | Epoch: 16/300
Accuracy of the mnist dataset: 0.101700
Accuracy of the mnist_m dataset: 0.089657
Ms: 40 | Mt: 40 | dcm: 0.02 | layer: 3 | Epoch: 17/300
Accuracy of the mnist dataset: 0.083700
Accuracy of the mnist_m dataset: 0.089657
Ms: 40 | Mt: 40 | dcm: 0.02 | layer: 3 | Epoch: 18/300
Accuracy of the mnist dataset: 0.087700
Accuracy of the mnist_m dataset: 0.089546
Ms: 40 | Mt: 40 | dcm: 0.02 | layer: 3 | Epoch: 19/300
Accuracy of the mnist dataset: 0.088800
Accuracy of the mnist_m dataset: 0.091323
Ms: 40 | Mt: 40 | dcm: 0.02 | layer: 3 | Epoch: 20/300
Accuracy of the mnist dataset: 0.089200
Accuracy of the mnist_m dataset: 0.090545
Ms: 40 | Mt: 40 | dcm: 0.02 | layer: 3 | Epoch: 21/300
Accuracy of the mnist dataset: 0.089000
Accuracy of the mnist_m dataset: 0.086435
Ms: 40 | Mt: 40 | dcm: 0.02 | layer: 3 | Epoch: 22/300
Accuracy of the mnist dataset: 0.071200
Accuracy of the mnist_m dataset: 0.087213
Ms: 40 | Mt: 40 | dcm: 0.02 | layer: 3 | Epoch: 23/300
Accuracy of the mnist dataset: 0.086800
Accuracy of the mnist_m dataset: 0.089435
Ms: 40 | Mt: 40 | dcm: 0.02 | layer: 3 | Epoch: 24/300
Accuracy of the mnist dataset: 0.088300
Accuracy of the mnist_m dataset: 0.090212
Ms: 40 | Mt: 40 | dcm: 0.02 | layer: 3 | Epoch: 25/300
Accuracy of the mnist dataset: 0.088000
Accuracy of the mnist_m dataset: 0.093990
Ms: 40 | Mt: 40 | dcm: 0.02 | layer: 3 | Epoch: 26/300
Accuracy of the mnist dataset: 0.096000
Accuracy of the mnist_m dataset: 0.089546
Ms: 40 | Mt: 40 | dcm: 0.02 | layer: 3 | Epoch: 27/300
Accuracy of the mnist dataset: 0.087100
Accuracy of the mnist_m dataset: 0.089879
Ms: 40 | Mt: 40 | dcm: 0.02 | layer: 3 | Epoch: 28/300
Accuracy of the mnist dataset: 0.087600
Accuracy of the mnist_m dataset: 0.089546
Ms: 40 | Mt: 40 | dcm: 0.02 | layer: 3 | Epoch: 29/300
Accuracy of the mnist dataset: 0.101600
Accuracy of the mnist_m dataset: 0.092767
Ms: 40 | Mt: 40 | dcm: 0.02 | layer: 3 | Epoch: 30/300
Accuracy of the mnist dataset: 0.095400
Accuracy of the mnist_m dataset: 0.090990
Ms: 40 | Mt: 40 | dcm: 0.02 | layer: 3 | Epoch: 31/300
Accuracy of the mnist dataset: 0.078500
Accuracy of the mnist_m dataset: 0.088990
Exception ignored in: <function _releaseLock at 0x7f74fc9ea9d0>
Traceback (most recent call last):
  File "/home/huseyin/anaconda3/envs/dannpy5/lib/python3.8/logging/__init__.py", line 223, in _releaseLock
    def _releaseLock():
KeyboardInterrupt:
Traceback (most recent call last):
  File "/home/huseyin/anaconda3/envs/dannpy5/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 779, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/home/huseyin/anaconda3/envs/dannpy5/lib/python3.8/multiprocessing/queues.py", line 116, in get
    return _ForkingPickler.loads(res)
  File "/home/huseyin/anaconda3/envs/dannpy5/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 282, in rebuild_storage_fd
    fd = df.detach()
  File "/home/huseyin/anaconda3/envs/dannpy5/lib/python3.8/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/home/huseyin/anaconda3/envs/dannpy5/lib/python3.8/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/home/huseyin/anaconda3/envs/dannpy5/lib/python3.8/multiprocessing/connection.py", line 502, in Client
    c = SocketClient(address)
  File "/home/huseyin/anaconda3/envs/dannpy5/lib/python3.8/multiprocessing/connection.py", line 630, in SocketClient
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "main.py", line 188, in <module>
    data_source = data_source_iter.next()
  File "/home/huseyin/anaconda3/envs/dannpy5/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/home/huseyin/anaconda3/envs/dannpy5/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 974, in _next_data
    idx, data = self._get_data()
  File "/home/huseyin/anaconda3/envs/dannpy5/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 941, in _get_data
    success, data = self._try_get_data()
  File "/home/huseyin/anaconda3/envs/dannpy5/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 792, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str))
RuntimeError: DataLoader worker (pid(s) 14331, 14332, 14333, 14334, 14335, 14336, 14337, 14338) exited unexpectedly